### ISSUE TITLE
Unable to Import from ...

### ISSUE THREAD

**Issue by jlallement** [headwirecom/aem-ide-tooling-4-intellij#36]
Hello,

I'm working on Intellij 2016.2.4 and I have the following exception everytime I try to "Import from" an AEM server

com.intellij.openapi.application.Application.invokeAndWait(Ljava/lang/Runnable;)V
java.lang.NoSuchMethodError: com.intellij.openapi.application.Application.invokeAndWait(Ljava/lang/Runnable;)V
	at com.headwire.aem.tooling.intellij.action.ImportFromServerAction.doImport(ImportFromServerAction.java:149)
	at com.headwire.aem.tooling.intellij.action.ImportFromServerAction.execute(ImportFromServerAction.java:84)
	at com.headwire.aem.tooling.intellij.action.AbstractProjectAction$1.run(AbstractProjectAction.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

My IntelliJ full version :

IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016
JRE: 1.8.0_112-release-b343 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

![capture1](https://cloud.githubusercontent.com/assets/11937325/24191898/8511da22-0eed-11e7-93c7-6fc590d4b80a.PNG)

Thx

**Comment by jlallement** [comment]
![capture](https://cloud.githubusercontent.com/assets/11937325/24191825/4234bc56-0eed-11e7-8369-d20bc054b9b6.PNG)

**Comment by schaefa** [comment]
Thank you for the report. This method was a recent addition to IntelliJ but I'm surprised it's not in 2016.2.

I will check and backport their code into the plugin if needed.

**Comment by schaefa** [comment]
It turns out that IntelliJ had this method in place but in 2016.2 they required an additional parameter. So I used this method signature instead and it should fix your issue.

Please try out this pre-release https://github.com/headwirecom/aem-ide-tooling-4-intellij/commit/8044c7ea00314bce74fc514f711dbf5e0fa330d8 and let me know if that works out.

**Comment by jlallement** [comment]
Hi,

Thx I will try it tomorrow and let you know. 


Envoyé de mon iPhone

**Comment by schaefa** [comment]
I guess this is not a problem anymore. Please re-open if that is still an issue.
